### ISSUE TITLE
ConnectTimeoutError

### ISSUE THREAD

**Issue by CCXXXI** [CCXXXI/discord-embeds-reader-bot#75]
```
2|reader   | ConnectTimeoutError: Connect Timeout Error
2|reader   |     at Timeout.onConnectTimeout (/root/discord-embeds-reader-bot/node_modules/undici/lib/core/connect.js:108:24)
2|reader   |     at Timeout.sentryWrapped [as _onTimeout] (/root/discord-embeds-reader-bot/node_modules/src/helpers.ts:95:1)
2|reader   |     at listOnTimeout (node:internal/timers:561:11)
2|reader   |     at processTimers (node:internal/timers:502:7) {
2|reader   |   code: 'UND_ERR_CONNECT_TIMEOUT'
2|reader   | }
```

```
2|reader   | TypeError: fetch failed
2|reader   |     at Object.processResponse (/root/discord-embeds-reader-bot/node_modules/undici/lib/fetch/index.js:197:23)
2|reader   |     at /root/discord-embeds-reader-bot/node_modules/undici/lib/fetch/index.js:930:38
2|reader   |     at node:internal/process/task_queues:141:7
2|reader   |     at AsyncResource.runInAsyncScope (node:async_hooks:202:9)
2|reader   |     at AsyncResource.runMicrotask (node:internal/process/task_queues:138:8)
2|reader   |     at runMicrotasks (<anonymous>)
2|reader   |     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
2|reader   |   cause: ConnectTimeoutError: Connect Timeout Error
2|reader   |       at Timeout.onConnectTimeout (/root/discord-embeds-reader-bot/node_modules/undici/lib/core/connect.js:108:24)
2|reader   |       at Timeout.sentryWrapped [as _onTimeout] (/root/discord-embeds-reader-bot/node_modules/src/helpers.ts:95:1)
2|reader   |       at listOnTimeout (node:internal/timers:561:11)
2|reader   |       at processTimers (node:internal/timers:502:7) {
2|reader   |     code: 'UND_ERR_CONNECT_TIMEOUT'
2|reader   |   }
2|reader   | }
```

**Comment by CCXXXI** [comment]
can't repro
